#!/usr/bin/ruby -w
# -*- coding: utf-8 -*-


$LOAD_PATH.unshift File.dirname( __FILE__ )


require 'rubygems'

require 'clusters'
require 'rake'
require 'shell'
require 'thread_pool'


class Thread
  def self.map list, &block
    list.collect do | each |
      self.start do
        block.call each
      end
    end.each do | each |
      each.join
    end
  end
end


class Run
  def initialize clusters
    @clusters = clusters
    @problem = Hash.new( [] )
    @node = Hash.new( [] )
    @novad = {}
    @pool = {}
  end


  def start
    begin
      cleanup_results
      start_novad
      cleanup_processes
      get_problem
      get_nodes

      main
    ensure
      cleanup
    end
  end


  ################################################################################
  private
  ################################################################################


  def main
    @clusters.each do | c |
      @pool[ c ] = ThreadPool.new( @node[ c ].size )

      # [FIXME] もうちょっと賢くディスパッチする
      @problem[ c ].each_with_index do | each, index |
        @pool[ c ].dispatch( each ) do
          nidx = index % @node[ c ].size
          dispatch c, @node[ c ][ nidx ], each
        end
      end
    end
    @pool.collect do | each |
      Thread.start do
        each[ 1 ].shutdown
      end
    end.each do | each |
      each.join
    end
  end


  def msg str
    puts str
  end


  def get_nodes
    Thread.map( @clusters ) do | each |
      msg "Getting node list on #{ each }..."

      Popen3::Shell.open do | shell |
        shell.on_stdout do | line |
          @node[ each ] = line.split( ' ' )
        end
        shell.on_stderr do | line |
          $stderr.puts line
        end

        shell.on_success do
          msg "#{ each }: #{ @node[ each ].size } nodes."
        end
        shell.on_failure do
          raise "get_nodes on #{ each } failed"
        end
        
        shell.exec "ssh dach000@#{ @novad[ each ] } ruby /home/dach000/nova/get_nodes.rb"
      end
    end
  end


  def get_problem
    Thread.map( @clusters ) do | each |
      msg "Getting problem list on #{ each }..."
      Popen3::Shell.open do | shell |
        shell.on_stdout do | line |
          @problem[ each ]  = line.split( ' ' )
        end
        shell.on_stderr do | line |
          $stderr.puts line
        end

        shell.on_success do
          msg "#{ each }: #{ @problem[ each ].size } pairs."
        end
        shell.on_failure do
          raise "get_problem on #{ each } failed"
        end
        
        shell.exec "ssh dach000@#{ @novad[ each ] } ruby /home/dach000/nova/get_problem.rb sample0"
      end
    end
  end


  def dispatch cluster, node, problem
    msg "Starting problem #{ problem } on #{ node }..."

    start = Time.now
    r = []
    Popen3::Shell.open do | shell |
      shell.on_stdout do | line |
        r << line.chomp
      end

      shell.on_stderr do | line |
        $stderr.puts line
      end

      shell.on_success do
        time = ( Time.now - start ).to_i
        msg "Problem #{ problem } on #{ node } finished successfully in #{ time }s."
        File.open( result_path( cluster, problem, time ), 'w' ) do | f |
          r.each do | l |
            f.puts l
          end
        end
      end

      shell.on_failure do
        raise "problem #{ problem } on #{ node } failed"
      end
      
      shell.exec "ssh dach000@#{ @novad[ cluster ] } ruby /home/dach000/nova/dispatch.rb #{ node } #{ problem }"
    end
  end


  def start_novad
    Thread.map( @clusters ) do | each |
      c = Clusters.list( each.to_sym )
      novad_node = [ c[ :list ].first, c[ :domain ] ].join( '.' )
      msg "Starting novad on #{ novad_node }..."
      begin
        system "ssh dach000@#{ novad_node } ruby /home/dach000/nova/novad.rb"
        msg "novad started on #{ novad_node }."
      rescue
        msg "Failed to start novad on #{ novad_node }"
      end
      @novad[ each ] = novad_node
    end
  end


  def cleanup_processes
    Thread.map( @clusters ) do | each |
      msg "Cleaning up processes on #{ each }..." 
      gxpc_init each
      gxpc_killall each
      gxpc_dachmon each
      gxpc_quit each
    end
  end


  def gxpc_init cluster
    sh "ssh dach000@#{ @novad[ cluster ] } gxpc quit", :verbose => false
    sh "ssh dach000@#{ @novad[ cluster ] } gxpc use ssh #{ cluster }", :verbose => false

    Popen3::Shell.open do | shell |
      shell.on_success do
        msg "gxpc explore on #{ cluster } succeeded."
      end
      shell.on_failure do
        raise "gxpc explore on #{ cluster } failed."
      end
      first = Clusters.list( cluster.to_sym )[ :list ].first.tr( cluster, '' )
      last = Clusters.list( cluster.to_sym )[ :list ].last.tr( cluster, '' )
      shell.exec "ssh dach000@#{ @novad[ cluster ] } gxpc explore #{ cluster }[[#{ first }-#{ last }]]"
    end
  end


  # [???] ほかに pkill すべきプロセスは？？
  # [???] pkill する順番は？
  def gxpc_killall cluster
    sh "ssh dach000@#{ @novad[ cluster ] } gxpc e pkill detect3", :verbose => false
    sh "ssh dach000@#{ @novad[ cluster ] } gxpc e pkill match2", :verbose => false
    sh "ssh dach000@#{ @novad[ cluster ] } gxpc e pkill mask3", :verbose => false
    sh "ssh dach000@#{ @novad[ cluster ] } gxpc e pkill sex", :verbose => false
    sh "ssh dach000@#{ @novad[ cluster ] } gxpc e pkill imsub3vp3", :verbose => false
  end


  def gxpc_dachmon cluster
    sh "ssh dach000@#{ @novad[ cluster ] } gxpc e /home/dach000/nova/dachmon.rb", :verbose => false
  end


  def gxpc_quit cluster
    sh "ssh dach000@#{ @novad[ cluster ] } gxpc quit", :verbose => false
  end


  def cleanup
    Thread.map( @novad ) do | each |
      msg "Cleaning up on #{ each[ 0 ] }..."
      sh "ssh dach000@#{ each[ 1 ] } ruby /home/dach000/nova/quit.rb", :verbose => false
    end
  end


  def cleanup_results
    msg 'Cleaning up old *.results...'
    results.each do | each |
      FileUtils.rm each, :verbose => false
    end
  end


  def results
    @clusters.collect do | each |
      Dir.glob File.join( result_dir( each ), '*.result' )
    end.flatten
  end


  def result_path cluster, job, sec
    File.join result_dir( cluster ), "#{ job }.in#{ sec }s.result"
  end


  def result_dir cluster_name
    File.join File.dirname( __FILE__ ), 'results', cluster_name
  end
end


run = Run.new( ARGV )
run.start


### Local variables:
### mode: Ruby
### coding: utf-8-unix
### indent-tabs-mode: nil
### End:
